library(ellmer)
library(magick)

# generate_story_tool <- function(
#     user_prompt,
#     genre = "fantasy",
#     struc = "Hero's Journey",
#     num_paras = "5"
# ) {
#   generate_story(
#     user_prompt = user_prompt,
#     genre = genre,
#     struc = struc,
#     num_paras = as.integer(num_paras)
#   )
# }


# Prompt ellmer to generate code for registering your tool:
# ellmer::create_tool_def(generate_story, chat = ellmer::chat_google_gemini(model = "gemini-2.0-flash"))
# ellmer::create_tool_def(generate_image_prompts, chat = ellmer::chat_google_gemini(model = "gemini-2.0-flash"))
# ellmer::create_tool_def(generate_images, chat = ellmer::chat_google_gemini(model = "gemini-2.0-flash"))


tool_gs <- tool(
  generate_story,
  "Generate a Fictional Story",
  user_prompt = type_string("Prompt about story"),
  num_paras = type_integer(
    "Number of paragraphs in the generated story.
Default is 5.",
    required = FALSE
  ),
  genre = type_string(
    "Genre of the story. One of \"adventure\",
\"horror\", \"scifi\", \"mystery\", \"thriller\",
\"fantasy\", \"comedy\", \"drama\", \"detective\",
\"satire\", \"supernatural\", \"romance\" or
\"western\"",
    required = FALSE
  ),
  struc = type_string(
    "Structure of the story. One of \"Hero's
Journey\", \"Three Act Structure\", \"Seven-Point
Story Structure\", \"Freytag's Pyramid\", \"Story
Circle\", \"Save The Cat\" or \"Fichtean Curve\"",
    required = FALSE
  )
)


tool_gp <- tool(
  generate_image_prompts,
  "Generate Image Prompts from story",
  story = type_string("Provide the story text generated by
`generate_story`")
)


# tool_gi <- tool(
#   generate_images,
#   "Get all images corresponding to prompts.",
#   image_prompts = type_array(
#     "A vector of prompts that describe what to draw",
#     items = type_string("A prompt")
#   ),
#   style = type_string(
#     "A character string specifying the desired style.
# Choices are: 'anime', 'comics', 'lego_movie', 'play_doh',
# 'ethereal_fantasy', 'isometric', 'line_art', 'origami',
# 'pixel_art', 'abstract', 'impressionist', 'renaissance',
# 'watercolor', 'biomechanical', 'retro_futuristic',
# 'fighting_game', 'mario', 'pokemon', 'street_fighter',
# 'horror', 'manga', 'space', 'paper_mache', 'tilt_shift'.
# Defaults to 'anime'.",
#     required = FALSE
#   )
# )

# my_tool <- tool(
#   generate_story_tool,
#   "Generates a story based on a user prompt.",
#   user_prompt = type_string("The prompt to
# generate a story from."),
#   genre = type_string(
#     "The genre of the story. Defaults to
# `\"adventure\"`.",
#     required = FALSE
#   ),
#   struc = type_string(
#     "The structure of the story. Defaults to
# `\"Hero's Journey\"`.",
#     required = FALSE
#   ),
#   num_paras = type_integer(
#     "The number of paragraphs in the story.
# Defaults to 5.",
#     required = FALSE
#   )
# )



chat <- ellmer::chat_google_gemini(
  model = "gemini-2.0-flash",
  system_prompt = paste(
    "1. If the user requests a story, ALWAYS use the 'Generate a Fictional Story' tool.",
    "2. After producing the story, display it to the user and ask 'Are you okay to proceed with illustration?'",
    "3. If the user replies with 'no', rerun the story generation.",
    "4. If the user replies 'yes', use the 'Generate image prompts' tool on the story.",
    "Do not show the output of the 'Generate image prompts' tool to the user."
  )
)
chat$register_tool(tool_gs)
chat$register_tool(tool_gp)
# chat$register_tool(tool_gi)

live_browser(chat)
