#' Generate Image Prompts using LLM
#'
#' @param story Character. Provide the story text generated by `generate_story`
# @param system_prompt Character. System prompt for the client that generates prompts for creating images. Default system prompt is specified by an internal function that provides an example. See `storytelling:::generate_image_prompts_system_prompt`. If you provide it yourself, make sure you specify the model generates the same number of prompts as the length of story
#' @param chat_fn Ellmer client function. Default is `ellmer::chat_google_gemini`
#' @param model LLM model. Default is `"gemini-2.0-flash"`
#' @param ... Additional named arguments that go in `chat_fn`. You may include the API key here using `api_key` argument, but it is recommended to provide the API key in your `.Renviron` file using `usethis::edit_r_environ()`. For Gemini, you may get an API key [here](https://ai.google.dev/gemini-api/docs/api-key). See [ellmer docs](https://ellmer.tidyverse.org/) for more provider options
#'
#' @returns Character vector containing prompts for images of length equal to `story`
#' @export
#'
#' @examples
#' \dontrun{
#' library(storytelling)
#' user_prompt <- "Tell me a story about a dragon who turned into a human."
#' story <- generate_story(user_prompt)
#' image_prompts <- generate_image_prompts(story)
#' }
generate_image_prompts <- function(story,
                                   # system_prompt = NULL,
                                   chat_fn = ellmer::chat_google_gemini,
                                   model = "gemini-2.0-flash",
                                   ...){

  # if (is.null(system_prompt)){
    system_prompt <- generate_image_prompts_system_prompt(length(story))
  # }

  client <- make_chat(
    chat_fn,
    system_prompt = system_prompt,
    model = model,
    ...
  )

  client$chat_structured(
    story,
    type = ellmer::type_array(
      paste0("Return exactly ",  length(story),  " paragraphs, as an array. Each array element is a paragraph. Do not return explanations or any text outside the array. Each paragraph must be self-contained, i.e., do not use blank lines or newlines to separate paragraphs inside elements."),
      items = ellmer::type_string()
    )
  )
}
